---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure apt cache is up to date
      apt: update_cache=yes

    - name: ensure ca certificates are installed
      apt: pkg=ca-certificates state=present

    - name: ensure apt supports https
      apt: pkg=apt-transport-https state=present

    - name: ensure passenger key is present
      apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7

    - name: ensure passenger repository is in apt sources
      apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger wheezy main' state=present

    - name: ensure nginx-extras is at the latest version
      apt: pkg=nginx-extras state=latest
      notify:
      - reload nginx

    - name: ensure passenger is at the latest version
      apt: pkg=passenger state=latest
      notify:
      - reload nginx

    - name: ensure passenger_root is defined in nginx configuration
      lineinfile: dest=/etc/nginx/nginx.conf line="passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;" insertafter="# passenger_root"
      notify:
      - reload nginx

    - name: ensure passenger_ruby is defined in nginx configuration
      lineinfile: dest=/etc/nginx/nginx.conf line="passenger_ruby /usr/bin/passenger_free_ruby;" insertafter="# passenger_ruby"
      notify:
      - reload nginx

    - name: ensure nginx virtual host configuration is present
      copy: src=files/fund.nginx.conf dest=/etc/nginx/sites-enabled/fund owner=root group=root mode=0644
      notify:
      - reload nginx

    - name: ensure deployer user is present
      user: name=deployer comment="Capistrano Deployer" shell=/bin/bash

    - name: ensure deployer authorized_key is present
      authorized_key: user=deployer key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP37RMFj1ZofwBLLwJRQjV9X9CtzIRE19kIJVrGN6z8XzPx8ltTzz185/dY2b7cx9I6HOhXZA5YPAEa31dcAdpITjsx5LYvmK7Xddl5KS1FnP5FEz7/NRpQDgPGD4+2f+gORhWcFGN3J/ETr129IZ0lg+O0t6TONntS7CsFU4v1lzbk8VqcEueEWivVN2J6OMBbb0dX4JsCC/JdhnI46GpdAc9m+M7lql6sEwVPZFJhCUCfrw4LSk1loRQm3VS1JhOqJT7xCBq0/DgVHyitPkiCyrkhQlSyuDO6pk7vsE08sIIf8QQKRwHmM1dL/PB8TXTDx63uyk4rP4ULURzD3sb"

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
